# Generated by Django 4.1 on 2023-10-23 09:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_alter_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
